import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../../styles/Gagym.module.css";
import logo from "../public/logo.png";
import "bootstrap/dist/css/bootstrap.min.css";
import AppBar from "../../components/appbar";

interface HomeProp {
  home: Home;
}

interface Home {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}

const gagymList = ({ home }: HomeProp) => {
  return (
    <div className={styles.container}>
      <AppBar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.div}>
          {/*첫줄*/}
          <div className="d-flex">
            <div className={styles.img}>
              <div className="row-vh d-flex flex-column">
                <img src="/gymimg/1 (1).jpg" />
                <div className="mt-2">
                  <a href="/gagym/gagym-detail[1]">
                    <h6>강남 화이트짐</h6>
                  </a>
                  <p className={styles.p}>서울특별시 강남구 도곡로3길 19</p>
                </div>
              </div>
            </div>
            <div className={styles.img}>
              <div className="row-vh d-flex flex-column">
                <img src="/gymimg/2 (1).jpg" />
                <div className="mt-2">
                  <h6>논현 REGENT 프라이빗짐</h6>
                  <p className={styles.p}>서울특별시 강남구 논현로119길 23</p>
                </div>
              </div>
            </div>
            <div className={styles.img}>
              <div className="row-vh d-flex flex-column">
                <img src="/gymimg/3 (1).jpg" />
                <div className="mt-2">
                  <h6>대치 로그짐</h6>
                  <p className={styles.p}>서울특별시 강남구 삼성로 317</p>
                </div>
              </div>
            </div>
          </div>
          {/*두번째줄*/}
          <div className="d-flex">
            <div className={styles.img}>
              <div className="row-vh d-flex flex-column">
                <img src="/gymimg/4 (1).jpg" />
                <div className="mt-2">
                  <h6>대치 휘트니스G</h6>
                  <p className={styles.p}>서울 강남구 역삼로 542</p>
                </div>
              </div>
            </div>
            <div className={styles.img}>
              <div className="row-vh d-flex flex-column">
                <img src="/gymimg/5 (1).jpg" />
                <div className="mt-2">
                  <h6>선릉 바디스페이스</h6>
                  <p className={styles.p}>서울특별시 강남구 테헤란로 311</p>
                </div>
              </div>
            </div>
            <div className={styles.img}>
              <div className="row-vh d-flex flex-column">
                <img src="/gymimg/6 (1).jpg" />
                <div className="mt-2">
                  <h6>선릉 보리스짐</h6>
                  <p className={styles.p}>서울특별시 강남구 선릉로94길 7</p>
                </div>
              </div>
            </div>
          </div>
          {/*세번째줄*/}
          <div className="d-flex">
            <div className={styles.img}>
              <div className="row-vh d-flex flex-column">
                <img src="/gymimg/7 (1).jpg" />
                <div className="mt-2">
                  <h6>압구정 로그짐</h6>
                  <p className={styles.p}>서울특별시 강남구 압구정로28길 40</p>
                </div>
              </div>
            </div>
            <div className={styles.img}>
              <div className="row-vh d-flex flex-column">
                <img src="/gymimg/8 (1).jpg" />
                <div className="mt-2">
                  <h6>언주 아트짐 토탈휘트니스</h6>
                  <p className={styles.p}>서울특별시 강남구 논현로 626</p>
                </div>
              </div>
            </div>
            <div className={styles.img}>
              <div className="row-vh d-flex flex-column">
                <img src="/gymimg/9 (1).jpg" />
                <div className="mt-2">
                  <h6>역삼 F&G휘트니스</h6>
                  <p className={styles.p}>서울특별시 강남구 테헤란로25길 7</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/*페이지네이션 시작
        <div>
          <button onClick={() => Router.push(`/?page=${this.props.page - 1}`)}>
            PREV
          </button>
          <button onClick={() => Router.push(`/?page=${this.props.page + 1}`)}>
            NEXT
          </button>
        </div>
        페이지네이션 끝*/}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

// 여기 함수부분의 코드를 실행하여 반환 값을 컴포넌트 속성을 넣어줌

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/homes/1");

  const home: Home = await res.json();

  // 여기에 prop: {속성객체}

  // 속성객체를 컴포넌트의 속성을 넣어줌

  return { props: { home } };
}

export default gagymList;
