import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../../styles/Gagymdetail.module.css";
import { useRouter } from "next/router";
import logo from "../public/logo.png";
import "bootstrap/dist/css/bootstrap.min.css";
import AppBar from "../../components/appbar";

interface HomeProp {
  home: Home;
}

interface Home {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}

const gagymDetail = ({ home }: HomeProp) => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <AppBar />

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.div}>
          {/*align-items: flex-start*/}
          <div className="d-flex mt-5">
            <div>
              <img src="/gymimg/1 (1).jpg" className={styles.src} />
            </div>
            <div style={{ width: "520px" }}>
              <h3>강남 화이트짐</h3>
              <h6>서울특별시 강남구 도곡로3길 19, 서희스타힐스 지하1층</h6>
              <h6>0504-3172-6899</h6>
              <p className={styles.p}>
                [운영시간]
                <br />
                평일 : 06:00~24:00
                <br />
                주말 :10:00~18:00
                <br />
                휴관일 : 공휴일, 매월 둘째, 넷째 주 일요일
              </p>
              <button
                type="button"
                className="btn btn-outline-dark btn-lg mt-4"
                style={{ width: "400px" }}
                onClick={() => {
                  router.push(`/reservation`);
                }}
              >
                예약하러 가기
              </button>
            </div>
          </div>
          {/*강사소개/이용권/헬스장사진/부가서비스/공지사항 시작*/}
          <h3 className={styles.h3}>강사소개</h3>
          <div className="d-flex align-items-center mt-3">
            <img src="/people.jpg" className={styles.img} />
            <div>
              <p className="d-flex mb-1">
                <u>강사이름</u>
              </p>
              <p>박이슬</p>
              <p className="d-flex mb-1">
                <u>강사 한줄 소개</u>
              </p>
              <p>강사 박이슬 입니다.</p>
              <p className="d-flex mb-1">
                <u>전문분야</u>
              </p>
              <p>근력 운동, 유산소 운동 등</p>
            </div>
          </div>
          <h3 className={styles.h3}>이용권</h3>
          {/*P.T*/}
          <div>
            <p className="d-flex justify-content-center mt-3">
              <u>P.T</u>
            </p>
            <button type="button" className={styles.btn}>
              1회
            </button>
            <button type="button" className={styles.btn}>
              10회
            </button>
            <button type="button" className={styles.btn}>
              30회
            </button>
          </div>
          {/*헬스*/}
          <div>
            <p className="d-flex justify-content-center mt-5">
              <u>헬스</u>
            </p>
            <button type="button" className={styles.btn}>
              1개월
            </button>
            <button type="button" className={styles.btn}>
              3개월
            </button>
            <button type="button" className={styles.btn}>
              6개월
            </button>
            <button type="button" className={styles.btn}>
              12개월
            </button>
          </div>
          {/*필라테스*/}
          <div>
            <p className="d-flex justify-content-center mt-5">
              <u>필라테스</u>
            </p>
            <button type="button" className={styles.btn}>
              1개월
            </button>
            <button type="button" className={styles.btn}>
              3개월
            </button>
            <button type="button" className={styles.btn}>
              6개월
            </button>
            <button type="button" className={styles.btn}>
              12개월
            </button>
          </div>
          {/*요가*/}
          <div>
            <p className="d-flex justify-content-center mt-5">
              <u>요가</u>
            </p>
            <button type="button" className={styles.btn}>
              1개월
            </button>
            <button type="button" className={styles.btn}>
              3개월
            </button>
            <button type="button" className={styles.btn}>
              6개월
            </button>
            <button type="button" className={styles.btn}>
              12개월
            </button>
          </div>
          <h3 className={styles.h3}>헬스장 사진</h3>
          <div className="mt-3">
            <img
              src="/gymimg/1 (1).jpg"
              style={{ width: "150px" }}
              className="border border-light"
            />
            <img
              src="/gymimg/1 (2).jpg"
              style={{ width: "150px" }}
              className="border border-light"
            />
            <img
              src="/gymimg/1 (3).jpg"
              style={{ width: "150px" }}
              className="border border-light"
            />
            <img
              src="/gymimg/1 (4).jpg"
              style={{ width: "150px" }}
              className="border border-light"
            />
          </div>
          <h3 className={styles.h3}>부가서비스</h3>
          <div>부가부가부가서비스입니다.</div>
          <h3 className={styles.h3}>공지사항</h3>
          <div className="mb-5">공지공지공지사항입니다.</div>

          {/*강사소개/이용권/헬스장사진/부가서비스/공지사항 끝*/}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

// 여기 함수부분의 코드를 실행하여 반환 값을 컴포넌트 속성을 넣어줌

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/homes/1");

  const home: Home = await res.json();

  // 여기에 prop: {속성객체}

  // 속성객체를 컴포넌트의 속성을 넣어줌

  return { props: { home } };
}

export default gagymDetail;
