import React from "react";

import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";
import "bootstrap/dist/css/bootstrap.min.css";
import HomeLogo from "../../components/homelogo";

interface HomeProp {
  home: Home;
}

interface Home {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}

const login = ({ home }: HomeProp) => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomeLogo />
        <button type="button" className="btn btn-dark mt-3">
          회원
        </button>
        <form className="mt-5 row-vh d-flex flex-column align-items-end">
          <div className="row mb-3">
            <label className="col-sm-3 col-form-label">회원명</label>
            <div className="col-sm-6">
              <input
                type="email"
                className="form-control"
                id="inputEmail3"
              ></input>
            </div>
          </div>
          <div className="row mb-3">
            <label className="col-sm-5 col-form-label">전화번호 끝 4자리</label>
            <div className="col-sm-5">
              <input
                type="password"
                className="form-control"
                id="inputPassword3"
              ></input>
            </div>
          </div>
        </form>

        <button
          type="button"
          className="btn btn-outline-dark btn-sm mt-2"
          onClick={() => {
            router.push(`/mypage/mypage`);
          }}
        >
          로그인
        </button>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

// 여기 함수부분의 코드를 실행하여 반환 값을 컴포넌트 속성을 넣어줌

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/homes/1");

  const home: Home = await res.json();

  // 여기에 prop: {속성객체}

  // 속성객체를 컴포넌트의 속성을 넣어줌

  return { props: { home } };
}

export default login;
