import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../../styles/Mypage.module.css";
import { useRouter } from "next/router";
import "bootstrap/dist/css/bootstrap.min.css";
import AppBar from "../../components/appbar";

interface HomeProp {
  home: Home;
}

interface Home {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}

const mypage = ({ home }: HomeProp) => {
  const router = useRouter();

  return (
    <div>
      <AppBar />

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.div}>
          {/*진행중인 예약내역*/}
          <div className="d-flex">
            <p className={styles.p}>진행중인 예약내역</p>
          </div>
          <table className="table ">
            <thead>
              <th>내 지역</th>
              <th>헬스장 명</th>
              <th>예약번호</th>
              <th>구매한 이용권</th>
              <th>현재 남은 이용횟수 이용권</th>
            </thead>
            <tbody>
              <tr>
                <td>서울</td>
                <td>대치휘트니스G</td>
                <td>21-04186</td>
                <td>10회</td>
                <td>9회</td>
              </tr>
            </tbody>
          </table>
          {/*예약내역*/}
          <div className="d-flex mt-5">
            <p className={styles.p}>예약내역</p>
            <button
              type="button"
              className="btn btn-secondary btn-sm mx-4"
              style={{ width: "80px;", height: "30px" }}
            >
              임시
            </button>
          </div>
          <table className="table">
            <thead>
              <th>예약번호</th>
              <th>헬스장 명</th>
              <th>이용권</th>
              <th>이용가격</th>
              <th>비고</th>
            </thead>
            <tbody>
              <tr>
                <td>21-04164</td>
                <td>대치휘트니스G</td>
                <td>10회</td>
                <td>400,000원</td>
                <td>미완료</td>
              </tr>
            </tbody>
          </table>
          {/*>PT일지 목록*/}
          <div className="d-flex mt-5">
            <p className={styles.p}>PT일지 목록</p>
            <button
              type="button"
              className="btn btn-secondary btn-sm mx-4"
              style={{ width: "80px;", height: "30px" }}
              onClick={() => {
                router.push("./diary/diary-list");
              }}
            >
              상세보기
            </button>
          </div>
          <table className="table">
            <thead>
              <th>일자</th>
              <th>식단내용</th>
              <th>운동내용</th>
              <th>문의사항</th>
              <th>담당강사</th>
              <th>강사피드백</th>
            </thead>
            <tbody>
              <tr>
                <td>10/25</td>
                <td>(아침) 고구마/우유</td>
                <td>PT + 런닝2시간</td>
                <td>-</td>
                <td>-</td>
                <td>미완료</td>
              </tr>
              <tr>
                <td>10/25</td>
                <td>(아침) 고구마/우유</td>
                <td>PT + 런닝2시간</td>
                <td>-</td>
                <td>-</td>
                <td>미완료</td>
              </tr>
            </tbody>
          </table>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

// 여기 함수부분의 코드를 실행하여 반환 값을 컴포넌트 속성을 넣어줌

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/homes/1");

  const home: Home = await res.json();

  // 여기에 prop: {속성객체}

  // 속성객체를 컴포넌트의 속성을 넣어줌

  return { props: { home } };
}

export default mypage;
