import React from "react";

import Head from "next/head";
import styles from "../../styles/Login.module.css";
import { useRouter } from "next/router";
import "bootstrap/dist/css/bootstrap.min.css";
import HomeLogo from "../../components/homelogo";

const Login = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomeLogo />
        <button type="button" className="btn btn-dark mt-3">
          회원
        </button>
        <form className="mt-5 row-vh d-flex flex-column align-items-end justify-content-space-evenly">
          <div>
            <div className={styles.divm}>
              <label className={styles.label}>회원명</label>
              <input
                type="text"
                className="form-control"
                style={{ width: "150px" }}
              ></input>
            </div>
          </div>
          <div className={styles.divm}>
            <label className={styles.label}>전화번호</label>

            <div>
              <input
                type="password"
                className="form-control"
                style={{ width: "150px" }}
              ></input>
            </div>
          </div>
        </form>

        <button
          type="button"
          className="btn btn-outline-dark btn-sm mt-5"
          onClick={() => {
            router.push(`/mypage/mypage`);
          }}
        >
          로그인
        </button>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Login;
