import React from "react";
import Head from "next/head";
import styles from "../../../styles/mypage.module.css";
import { useRouter } from "next/router";
import { AppDispatch, RootState } from "../../../provider";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import "bootstrap/dist/css/bootstrap.min.css";
import AppBar from "../../../components/appbar"
import { ReservationList } from "../../../provider/modules/reservation";
import {
  requestFetchPagingReservation,
  requestFetchReservationItem,
  requestRemoveReservationNext,
  // requestRemoveReservationPaging,
} from "../../../middleware/modules/reservation";


interface HomeProp {
  home: Home;
}

interface Home {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}

const mypage = ({ home }: HomeProp) => {
  const router = useRouter();
  const dispatch = useDispatch<AppDispatch>();
  const reservation = useSelector((state: RootState) => state.reservation);

  useEffect(() => {
    if (!reservation.isFetched) {
      dispatch(
        requestFetchPagingReservation({
          page: 0,
          size: reservation.pageSize,
        })
      );
    }
  }, [dispatch, reservation.isFetched, reservation.pageSize]);

  const handlePageChanged = (page: number) => {
    console.log("--page: " + page);
    dispatch(
      requestFetchPagingReservation({
        page,
        size: reservation.pageSize,
      })
    );
  };
  return (
    <div>
      <AppBar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{ width: "60vw" }}>
        <div className={styles.div}>
          {/*진행중인 예약내역*/}
          <div className="d-flex mx-auto">
            <p className={styles.p}>진행중인 예약내역</p>
          </div>
          <table className="table ">
            <thead>
              <th>내 지역</th>
              <th>헬스장 명</th>
              <th>예약번호</th>
              <th>구매한 이용권</th>
              <th>남은 횟수</th>
            </thead>
            <tbody>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>
          {/*예약내역*/}
          <div className="d-flex mt-5">
            <p className={styles.p}>예약내역</p>
          </div>
          <table className="table">
            <thead>
              <th>예약번호</th>
              <th>헬스장 명</th>
              <th>강사 명</th>
              <th>이용권</th>
              <th>이용가격</th>
              <th>상세보기</th>
            </thead>
            <tbody>
              {reservation.data.map((item,index)=>(
              <tr onClick={() => {
                router.push(`/mypage/myreservation/detail/${item.id}`);
              }} style={{ cursor:"pointer" }}>
              <td>{item.id}</td>
              <td>{item.gymName}</td>
              <td>{item.trainerName}</td>
              <td>{item.boughtService}</td>
              <td>{item.price}</td>
              <td><button
              type="button"
              className="btn btn-secondary btn-sm mx-4"
              style={{ width: "80px;", height: "30px" }}
              onClick={() => {
                router.push(`/mypage/myreservation/detail/${item.id}`);
              }}
            >
              상세보기
            </button></td>
            </tr>
              ))}
            </tbody>
          </table>
          {/* >PT일지 목록
          <div className="d-flex mt-5">
            <p className={styles.p}>PT일지 목록</p>
            <button
              type="button"
              className="btn btn-secondary btn-sm mx-4"
              style={{ width: "80px;", height: "30px" }}
              onClick={() => {
                router.push("./diary/diary-list");
              }}
            >
              상세보기
            </button>
          </div>
          <table className="table">
            <thead>
              <th>일자</th>
              <th>식단내용</th>
              <th>운동내용</th>
              <th>문의사항</th>
              <th>담당강사</th>
              <th>강사피드백</th>
            </thead>
            <tbody>
              <tr>
                <td>10/25</td>
                <td>(아침) 고구마/우유</td>
                <td>PT + 런닝2시간</td>
                <td>-</td>
                <td>-</td>
                <td>미완료</td>
              </tr>
              <tr>
                <td>10/25</td>
                <td>(아침) 고구마/우유</td>
                <td>PT + 런닝2시간</td>
                <td>-</td>
                <td>-</td>
                <td>미완료</td>
              </tr>
            </tbody>
          </table> */}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export async function getServerSideProps() {
  // const res = await fetch("https://jsonplaceholder.typicode.com/users");
  // const res = await axios.get<GymInfo[]>("https://jsonplaceholder.typicode.com/photos?_start=0&_limit=1");
  // const reservation = res.data;


  // const addreserve: ReservationItem = await res.json();
  // 여기에 prop: {속성객체}

  // 속성객체를 컴포넌트의 속성을 넣어줌

  const reservation =[
    {
      id : 1,
      gymName:"테스트헬스장",
      trainerName:"테스트강사",
      boughtService:"테스트서비스",
      price:"테스트가격",
      memberName : "테스트이름",
      memberPhone : "테스트연락처",
      memberRequest : "테스트문의사항",
    }
  ]

  return { props: { reservation } };
}

// 여기 함수부분의 코드를 실행하여 반환 값을 컴포넌트 속성을 넣어줌

export default mypage;